### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/ai-assist#6]
- [x] 支持多行输入，可能支持动态行数，可能最大 4 行之类的，允许滚动条
- [x] 修复多行输入后，显示仍然是单行，需要添加样式 `white-space: pre-wrap;`
- [x] 删除标签页有点麻烦
- [x] 支持编辑会话标签页名字
- [x] 修复 markdown 预览没有复制代码的功能
- [x] 修复 markdown 预览出现了错误的滚动条
- [x] markdown 代码显示复制按钮
- [x] 切换会话时自动滚动到底部（或者保持记录的位置）
- [x] 左上角的新会话按钮过于不明显，默认设置为主色
- [x] “复制会话”过于显眼，改变为更不明显的颜色
- [x] feat: 支持快捷输入提示语
- [x] feat: i18n 支持
- [x] fix: 修复 textarea 不能滚动的错误
- [x] fix: 修复侧边栏过多时滚动条位置不对的错误
- [x] feat: 支持导入导出会话
- [x] feat: 快捷提示语支持虚拟无限滚动
- [x] feat: 快捷提示语支持搜索英文 -- 替换为英文优先
- [x] feat: 需要阻止并发发送消息
- [x] fix: 修复操作按钮列没有正确出现横向滚动条的问题
- [x] feat: 添加 google 分析功能的使用频率，避免无限制的增加 feature
- [x] feat: 支持中断输出，支持重新开始输出
- [x] feat: 支持自定义快捷提示语 -- 简化，不再优先处理 i18n 的问题
- [ ] feat: 同步本地的会话到远端
- [ ] docs: 更新文档以说明如何自定义提示语与分享
- [x] feat: 支持配置自己的 open api key
- [ ] fix: 修复 markdown 中 code 标签单行过长在移动端没有正确添加滚动条的错误
- [ ] feat: 在文档主页声明记录保留时间为 3 个月（主要是为了与官方的 tokens 使用消耗做对照，确定实际使用的 tokens 和官方收取的费用一致）
- [x] feat: 更换消息提示的模式，将提示消息作为系统消息
- [ ] feat: 提示词无法积累或导入，例如希望某个标签页只做翻译、润色、检查错别字、总结、或者根据接口生成 mock 数据之类的
- [ ] feat: 支持对消息做更多操作 <https://blog.miniasp.com/post/2023/02/28/Useful-tool-ChatGPT-Toolkit>
- [ ] feat: 当开始识别时有更明确的提示，当发生错误时有更明确的提示，支持发生错误后重新生成
- [ ] feat: 支持全语音交互模式，过滤扬声器输出的声音
- [x] feat: 支持手动指定 access token 的方式
- [x] feat: 选择少数好用的会话，例如苏格拉底的风格
- [x] fix: 修复语言选择文字过大不适的感觉
- [ ] feat: 使用时传递 user 参数，避免多个用户之间共享相同的会话上下文
- [ ] feat: 更新日志添加自定义中间件 bunyan-logger，ref: <https://cabinjs.com/>
- [ ] fix: 修复用户输入之后没有自动翻页的错误
- [ ] fix: 修复 markdown 展示最后一个 p 节点没有删除 `margin-bottom` 的问题
- [ ] fix: 修复输入框计算高度导致的光标丢失，滚动条总是移动到顶部
- [ ] feat: 记录每条消息使用的 tokens 便于后续统计评估成本
- [ ] feat: 所有消息创建完成之后都不允许再次编辑，避免后续统计成本变得非常困难
- [ ] feat: 使用 gpt-token-utils 替换 gpt-tokenizer，见效整个 bundle 的大小
- [ ] fix: 修复在前端没有提示密码、用户、邮箱验证的问题，避免一直无法通过验证但又不知道原因
- [ ] feat: 禁用 chat 之外的功能，避免用户误入该页面
- [ ] feat: 实现共享的 prompts，例如翻译、润色、检查错别字、总结、或者根据接口生成 mock 数据之类的
